[package]
name = "mdmeow"
version = "1.7.2"
description = "MDmeow - a minimalist WYSIWYG Markdown editor"
authors = ["zakee039", "Ali Naderi"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "mdmeow_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
comrak = "0.54"
anyhow = "1"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
