import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../../docs');const require=createRequire(import.meta.url);const {chromium}=require('C:/Users/mamin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res)});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const report=[];const errors=[];
try{for(const width of [1440,375]){const page=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));
for(const file of ['index.html','en.html']){await page.goto(`http://127.0.0.1:${server.address().port}/${file}`);for(let cut=1;cut<=8;cut++){await page.evaluate(n=>location.hash=String(n),cut);await page.waitForFunction(n=>location.hash==='#'+n&&document.querySelector('.language-switch a').hash==='#'+n,cut);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('.scene.active img')].map(i=>i.decode()))});
const data=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth,head:[...document.querySelectorAll('.language-switch a')].map(a=>({text:a.textContent,right:a.getBoundingClientRect().right})),heading:document.querySelector('.scene.active h1,.scene.active h2')?.textContent}));report.push({width,file,cut,...data});
if(cut===1||cut===7)await page.screenshot({path:`${here}/qa/site-${width}-${file}-${cut}.jpg`,fullPage:true});
if(data.scroll>width||data.head.some(a=>a.right>width))errors.push(`Overflow: ${file} ${width} ${cut}`);}
await page.locator('.language-switch a').filter({hasText:file==='index.html'?'English':'中文'}).click();await page.waitForURL('**/'+(file==='index.html'?'en.html':'index.html')+'#8');}
await page.close();}}finally{await browser.close();server.close()}
fs.writeFileSync(here+'/qa/site-validation.json',JSON.stringify({errors,report},null,2));if(errors.length)throw Error(errors.join('\n'));console.log('Both languages: eight sections, desktop/mobile, images and language navigation passed.');

