// A small, hand-curated set of common emoji for the picker component and the
// `:shortcode:` input rule. Native Unicode only — no images, no CDN, no runtime
// dependency. Keep it compact: this is "the ones people actually type", not a
// full Unicode set.
//
// `e` = glyph, `n` = canonical shortcode (GitHub-style), `k` = extra search
// keywords (space-separated). `ALIASES` maps alternate shortcodes onto a
// canonical `n`.

export interface EmojiEntry {
  e: string;
  n: string;
  k: string;
}

export const EMOJI: EmojiEntry[] = [
  // --- smileys & emotion ---
  { e: "😀", n: "grinning", k: "smile happy face" },
  { e: "😃", n: "smiley", k: "happy joy smile" },
  { e: "😄", n: "smile", k: "happy joy laugh" },
  { e: "😁", n: "grin", k: "happy smile" },
  { e: "😆", n: "laughing", k: "haha lol satisfied" },
  { e: "😅", n: "sweat_smile", k: "hot relief phew" },
  { e: "🤣", n: "rofl", k: "rolling floor laughing lmao" },
  { e: "😂", n: "joy", k: "tears laughing cry funny" },
  { e: "🙂", n: "slightly_smiling_face", k: "smile" },
  { e: "🙃", n: "upside_down_face", k: "silly sarcasm" },
  { e: "😉", n: "wink", k: "flirt" },
  { e: "😊", n: "blush", k: "smile shy proud" },
  { e: "😇", n: "innocent", k: "angel halo" },
  { e: "🥰", n: "smiling_face_with_three_hearts", k: "love adore" },
  { e: "😍", n: "heart_eyes", k: "love crush" },
  { e: "🤩", n: "star_struck", k: "wow eyes excited" },
  { e: "😘", n: "kissing_heart", k: "kiss love" },
  { e: "😗", n: "kissing", k: "kiss" },
  { e: "😚", n: "kissing_closed_eyes", k: "kiss" },
  { e: "😙", n: "kissing_smiling_eyes", k: "kiss" },
  { e: "😋", n: "yum", k: "tongue delicious tasty" },
  { e: "😛", n: "stuck_out_tongue", k: "tongue cheeky" },
  { e: "😜", n: "stuck_out_tongue_winking_eye", k: "tongue wink joke" },
  { e: "🤪", n: "zany_face", k: "goofy crazy wild" },
  { e: "😝", n: "stuck_out_tongue_closed_eyes", k: "tongue prank" },
  { e: "🤑", n: "money_mouth_face", k: "rich dollar" },
  { e: "🤗", n: "hugs", k: "hug embrace" },
  { e: "🤭", n: "hand_over_mouth", k: "oops giggle" },
  { e: "🤫", n: "shushing_face", k: "quiet silence shh" },
  { e: "🤔", n: "thinking", k: "hmm consider think" },
  { e: "🤐", n: "zipper_mouth_face", k: "silence secret" },
  { e: "🤨", n: "raised_eyebrow", k: "skeptic suspicious" },
  { e: "😐", n: "neutral_face", k: "meh blank" },
  { e: "😑", n: "expressionless", k: "blank meh" },
  { e: "😶", n: "no_mouth", k: "silence speechless" },
  { e: "😏", n: "smirk", k: "smug sly" },
  { e: "😒", n: "unamused", k: "meh unimpressed" },
  { e: "🙄", n: "roll_eyes", k: "eyeroll annoyed" },
  { e: "😬", n: "grimacing", k: "awkward yikes" },
  { e: "🤥", n: "lying_face", k: "liar pinocchio" },
  { e: "😌", n: "relieved", k: "calm content" },
  { e: "😔", n: "pensive", k: "sad thoughtful" },
  { e: "😪", n: "sleepy", k: "tired" },
  { e: "🤤", n: "drooling_face", k: "drool" },
  { e: "😴", n: "sleeping", k: "zzz sleep tired" },
  { e: "😷", n: "mask", k: "sick ill face" },
  { e: "🤒", n: "face_with_thermometer", k: "sick fever ill" },
  { e: "🤕", n: "face_with_head_bandage", k: "hurt injured" },
  { e: "🤢", n: "nauseated_face", k: "sick gross" },
  { e: "🤮", n: "vomiting_face", k: "sick puke" },
  { e: "🤧", n: "sneezing_face", k: "sick achoo" },
  { e: "🥵", n: "hot_face", k: "heat sweating" },
  { e: "🥶", n: "cold_face", k: "freezing frozen" },
  { e: "😵", n: "dizzy_face", k: "confused stunned" },
  { e: "🤯", n: "exploding_head", k: "mind blown shocked" },
  { e: "🤠", n: "cowboy_hat_face", k: "cowboy yeehaw" },
  { e: "🥳", n: "partying_face", k: "party celebrate hat" },
  { e: "😎", n: "sunglasses", k: "cool shades" },
  { e: "🤓", n: "nerd_face", k: "geek glasses" },
  { e: "🧐", n: "monocle_face", k: "inspect fancy" },
  { e: "😕", n: "confused", k: "unsure" },
  { e: "😟", n: "worried", k: "concerned" },
  { e: "🙁", n: "slightly_frowning_face", k: "sad frown" },
  { e: "😮", n: "open_mouth", k: "surprise wow" },
  { e: "😯", n: "hushed", k: "surprised quiet" },
  { e: "😲", n: "astonished", k: "shocked amazed" },
  { e: "😳", n: "flushed", k: "embarrassed blush" },
  { e: "🥺", n: "pleading_face", k: "puppy eyes please beg" },
  { e: "😦", n: "frowning", k: "sad" },
  { e: "😧", n: "anguished", k: "distress" },
  { e: "😨", n: "fearful", k: "scared afraid" },
  { e: "😰", n: "cold_sweat", k: "nervous anxious" },
  { e: "😥", n: "disappointed_relieved", k: "phew sad" },
  { e: "😢", n: "cry", k: "sad tear" },
  { e: "😭", n: "sob", k: "cry bawling sad" },
  { e: "😱", n: "scream", k: "fear shock omg" },
  { e: "😖", n: "confounded", k: "frustrated" },
  { e: "😣", n: "persevere", k: "struggle" },
  { e: "😞", n: "disappointed", k: "sad let down" },
  { e: "😓", n: "sweat", k: "hard work nervous" },
  { e: "😩", n: "weary", k: "tired frustrated" },
  { e: "😫", n: "tired_face", k: "exhausted ugh" },
  { e: "🥱", n: "yawning_face", k: "bored tired" },
  { e: "😤", n: "triumph", k: "proud steam determined" },
  { e: "😡", n: "rage", k: "angry mad furious" },
  { e: "😠", n: "angry", k: "mad annoyed" },
  { e: "🤬", n: "cursing_face", k: "swearing angry" },
  { e: "😈", n: "smiling_imp", k: "devil evil" },
  { e: "👿", n: "imp", k: "devil angry" },
  { e: "💀", n: "skull", k: "dead death" },
  { e: "☠️", n: "skull_and_crossbones", k: "danger poison death" },
  { e: "💩", n: "poop", k: "crap shit hankey" },
  { e: "🤡", n: "clown_face", k: "clown" },
  { e: "👹", n: "japanese_ogre", k: "monster" },
  { e: "👻", n: "ghost", k: "boo halloween spooky" },
  { e: "👽", n: "alien", k: "ufo extraterrestrial" },
  { e: "🤖", n: "robot", k: "bot android" },
  { e: "🎃", n: "jack_o_lantern", k: "halloween pumpkin" },
  { e: "😺", n: "smiley_cat", k: "cat happy" },
  { e: "😸", n: "smile_cat", k: "cat grin" },
  { e: "😻", n: "heart_eyes_cat", k: "cat love" },
  { e: "😹", n: "joy_cat", k: "cat laugh" },
  { e: "🙀", n: "scream_cat", k: "cat shock" },

  // --- hearts & symbols ---
  { e: "❤️", n: "heart", k: "love red" },
  { e: "🧡", n: "orange_heart", k: "love" },
  { e: "💛", n: "yellow_heart", k: "love" },
  { e: "💚", n: "green_heart", k: "love" },
  { e: "💙", n: "blue_heart", k: "love" },
  { e: "💜", n: "purple_heart", k: "love" },
  { e: "🖤", n: "black_heart", k: "love dark" },
  { e: "🤍", n: "white_heart", k: "love" },
  { e: "🤎", n: "brown_heart", k: "love" },
  { e: "💔", n: "broken_heart", k: "heartbreak sad" },
  { e: "❣️", n: "heavy_heart_exclamation", k: "love" },
  { e: "💕", n: "two_hearts", k: "love" },
  { e: "💞", n: "revolving_hearts", k: "love" },
  { e: "💓", n: "heartbeat", k: "love pulse" },
  { e: "💗", n: "heartpulse", k: "love growing" },
  { e: "💖", n: "sparkling_heart", k: "love" },
  { e: "💘", n: "cupid", k: "love arrow" },
  { e: "💝", n: "gift_heart", k: "love present" },
  { e: "💟", n: "heart_decoration", k: "love" },
  { e: "💯", n: "100", k: "hundred perfect score" },
  { e: "💢", n: "anger", k: "mad comic" },
  { e: "💥", n: "boom", k: "explosion collision" },
  { e: "💫", n: "dizzy", k: "star spin" },
  { e: "💦", n: "sweat_drops", k: "water splash" },
  { e: "💨", n: "dash", k: "wind fast run" },
  { e: "🕳️", n: "hole", k: "gap" },
  { e: "💬", n: "speech_balloon", k: "comment talk chat" },
  { e: "💭", n: "thought_balloon", k: "think dream" },
  { e: "💤", n: "zzz", k: "sleep sleeping" },
  { e: "🔥", n: "fire", k: "lit flame hot" },
  { e: "⭐", n: "star", k: "favourite" },
  { e: "🌟", n: "star2", k: "glowing shine" },
  { e: "✨", n: "sparkles", k: "shiny stars magic new" },
  { e: "⚡", n: "zap", k: "lightning fast electric" },
  { e: "☀️", n: "sunny", k: "sun weather clear" },
  { e: "⛅", n: "partly_sunny", k: "cloud weather" },
  { e: "☁️", n: "cloud", k: "weather" },
  { e: "🌈", n: "rainbow", k: "pride colours" },
  { e: "☔", n: "umbrella", k: "rain weather" },
  { e: "❄️", n: "snowflake", k: "snow cold winter" },
  { e: "⛄", n: "snowman", k: "winter snow" },
  { e: "🌊", n: "ocean", k: "wave sea water" },
  { e: "💧", n: "droplet", k: "water drop" },

  // --- hands & people ---
  { e: "👋", n: "wave", k: "hello hi bye hand" },
  { e: "🤚", n: "raised_back_of_hand", k: "hand stop" },
  { e: "✋", n: "raised_hand", k: "high five stop hand" },
  { e: "🖐️", n: "hand", k: "raised fingers splayed" },
  { e: "🖖", n: "vulcan_salute", k: "spock star trek" },
  { e: "👌", n: "ok_hand", k: "perfect okay" },
  { e: "🤌", n: "pinched_fingers", k: "italian gesture" },
  { e: "🤏", n: "pinching_hand", k: "small tiny bit" },
  { e: "✌️", n: "v", k: "victory peace" },
  { e: "🤞", n: "crossed_fingers", k: "luck hope" },
  { e: "🤟", n: "love_you_gesture", k: "ily hand" },
  { e: "🤘", n: "metal", k: "rock horns" },
  { e: "🤙", n: "call_me_hand", k: "hang loose shaka" },
  { e: "👈", n: "point_left", k: "finger direction" },
  { e: "👉", n: "point_right", k: "finger direction" },
  { e: "👆", n: "point_up_2", k: "finger direction up" },
  { e: "👇", n: "point_down", k: "finger direction" },
  { e: "☝️", n: "point_up", k: "finger one" },
  { e: "👍", n: "+1", k: "thumbsup yes approve like good" },
  { e: "👎", n: "-1", k: "thumbsdown no disapprove dislike bad" },
  { e: "✊", n: "fist_raised", k: "power solidarity" },
  { e: "👊", n: "fist_oncoming", k: "punch bump" },
  { e: "🤛", n: "fist_left", k: "bump punch" },
  { e: "🤜", n: "fist_right", k: "bump punch" },
  { e: "👏", n: "clap", k: "applause bravo praise" },
  { e: "🙌", n: "raised_hands", k: "hooray celebration praise" },
  { e: "👐", n: "open_hands", k: "hug jazz" },
  { e: "🤲", n: "palms_up_together", k: "pray offer" },
  { e: "🤝", n: "handshake", k: "deal agreement" },
  { e: "🙏", n: "pray", k: "please thanks hope namaste" },
  { e: "✍️", n: "writing_hand", k: "write pen" },
  { e: "💅", n: "nail_care", k: "manicure polish" },
  { e: "💪", n: "muscle", k: "flex strong gym biceps" },
  { e: "🦾", n: "mechanical_arm", k: "prosthetic strong" },
  { e: "👀", n: "eyes", k: "look see watch" },
  { e: "👁️", n: "eye", k: "look see" },
  { e: "🧠", n: "brain", k: "smart think" },
  { e: "👶", n: "baby", k: "infant child" },
  { e: "🧑", n: "adult", k: "person" },
  { e: "👤", n: "bust_in_silhouette", k: "user person profile" },
  { e: "👥", n: "busts_in_silhouette", k: "users people group" },
  { e: "🚶", n: "walking", k: "pedestrian walk" },
  { e: "🏃", n: "runner", k: "run running exercise" },
  { e: "🕺", n: "man_dancing", k: "dance disco" },
  { e: "💃", n: "dancer", k: "dance flamenco" },

  // --- celebration & objects ---
  { e: "🎉", n: "tada", k: "party celebrate hooray confetti" },
  { e: "🎊", n: "confetti_ball", k: "party celebrate" },
  { e: "🎈", n: "balloon", k: "party birthday" },
  { e: "🎁", n: "gift", k: "present birthday box" },
  { e: "🎀", n: "ribbon", k: "bow present" },
  { e: "🎂", n: "birthday", k: "cake party" },
  { e: "🏆", n: "trophy", k: "win award champion" },
  { e: "🥇", n: "1st_place_medal", k: "gold win first" },
  { e: "🥈", n: "2nd_place_medal", k: "silver second" },
  { e: "🥉", n: "3rd_place_medal", k: "bronze third" },
  { e: "🏅", n: "medal_sports", k: "award win" },
  { e: "👑", n: "crown", k: "king queen royal" },
  { e: "💎", n: "gem", k: "diamond jewel valuable" },
  { e: "🔔", n: "bell", k: "notification alert ring" },
  { e: "🔕", n: "no_bell", k: "mute silent" },
  { e: "📢", n: "loudspeaker", k: "announce loud" },
  { e: "📣", n: "mega", k: "megaphone announce cheer" },
  { e: "💡", n: "bulb", k: "idea light lightbulb" },
  { e: "🔦", n: "flashlight", k: "torch light" },
  { e: "🔧", n: "wrench", k: "tool fix spanner" },
  { e: "🔨", n: "hammer", k: "tool build" },
  { e: "🛠️", n: "hammer_and_wrench", k: "tools build fix" },
  { e: "⚙️", n: "gear", k: "settings cog config" },
  { e: "🔩", n: "nut_and_bolt", k: "hardware" },
  { e: "🔗", n: "link", k: "chain url hyperlink" },
  { e: "📎", n: "paperclip", k: "attach clip" },
  { e: "📌", n: "pushpin", k: "pin location" },
  { e: "📍", n: "round_pushpin", k: "pin location map" },
  { e: "✂️", n: "scissors", k: "cut" },
  { e: "🖊️", n: "pen", k: "write ballpoint" },
  { e: "✏️", n: "pencil2", k: "write edit" },
  { e: "📝", n: "memo", k: "note write edit pencil" },
  { e: "📄", n: "page_facing_up", k: "document file" },
  { e: "📃", n: "page_with_curl", k: "document" },
  { e: "📑", n: "bookmark_tabs", k: "document" },
  { e: "📊", n: "bar_chart", k: "graph stats data" },
  { e: "📈", n: "chart_with_upwards_trend", k: "graph growth up" },
  { e: "📉", n: "chart_with_downwards_trend", k: "graph loss down" },
  { e: "📋", n: "clipboard", k: "copy list" },
  { e: "📅", n: "date", k: "calendar day" },
  { e: "📆", n: "calendar", k: "date schedule" },
  { e: "📁", n: "file_folder", k: "directory" },
  { e: "📂", n: "open_file_folder", k: "directory" },
  { e: "🗂️", n: "card_file_box", k: "organise archive" },
  { e: "💾", n: "floppy_disk", k: "save disk" },
  { e: "💿", n: "cd", k: "disc" },
  { e: "🔒", n: "lock", k: "secure closed private" },
  { e: "🔓", n: "unlock", k: "open" },
  { e: "🔑", n: "key", k: "password unlock" },
  { e: "🔍", n: "mag", k: "search zoom find magnify" },
  { e: "📦", n: "package", k: "box parcel shipping npm" },
  { e: "📧", n: "email", k: "mail envelope message" },
  { e: "📨", n: "incoming_envelope", k: "mail receive" },
  { e: "📚", n: "books", k: "library read" },
  { e: "📖", n: "book", k: "read open" },
  { e: "📓", n: "notebook", k: "notes" },
  { e: "🔖", n: "bookmark", k: "tag save" },
  { e: "🏷️", n: "label", k: "tag" },
  { e: "💰", n: "moneybag", k: "money cash rich" },
  { e: "💵", n: "dollar", k: "money cash bill" },
  { e: "💳", n: "credit_card", k: "payment money" },
  { e: "⏳", n: "hourglass_flowing_sand", k: "time loading wait" },
  { e: "⌛", n: "hourglass", k: "time done" },
  { e: "⏰", n: "alarm_clock", k: "time wake" },
  { e: "⏱️", n: "stopwatch", k: "timer time" },
  { e: "⌚", n: "watch", k: "time clock" },
  { e: "💻", n: "computer", k: "laptop pc code" },
  { e: "🖥️", n: "desktop_computer", k: "pc monitor" },
  { e: "⌨️", n: "keyboard", k: "type input" },
  { e: "🖱️", n: "computer_mouse", k: "click" },
  { e: "🖨️", n: "printer", k: "print" },
  { e: "📱", n: "iphone", k: "phone mobile smartphone" },
  { e: "🔋", n: "battery", k: "power charge" },
  { e: "🔌", n: "electric_plug", k: "power charge" },
  { e: "💊", n: "pill", k: "medicine drug" },
  { e: "💉", n: "syringe", k: "vaccine shot needle" },
  { e: "🧪", n: "test_tube", k: "science experiment lab" },
  { e: "🔬", n: "microscope", k: "science lab" },
  { e: "🔭", n: "telescope", k: "space astronomy" },
  { e: "🧲", n: "magnet", k: "attract" },
  { e: "🧹", n: "broom", k: "clean sweep" },
  { e: "🛒", n: "shopping_cart", k: "buy trolley" },
  { e: "🛏️", n: "bed", k: "sleep bedroom" },

  // --- travel & places ---
  { e: "🚀", n: "rocket", k: "launch ship space fast deploy" },
  { e: "🛸", n: "flying_saucer", k: "ufo alien" },
  { e: "✈️", n: "airplane", k: "flight travel plane" },
  { e: "🚁", n: "helicopter", k: "chopper fly" },
  { e: "🚗", n: "car", k: "auto vehicle drive" },
  { e: "🚕", n: "taxi", k: "cab" },
  { e: "🚌", n: "bus", k: "vehicle" },
  { e: "🚆", n: "train", k: "rail" },
  { e: "🚲", n: "bike", k: "bicycle cycle" },
  { e: "⛵", n: "boat", k: "sail ship" },
  { e: "🚢", n: "ship", k: "cruise boat" },
  { e: "⚓", n: "anchor", k: "ship boat" },
  { e: "🚧", n: "construction", k: "wip barrier work" },
  { e: "🚦", n: "vertical_traffic_light", k: "signal stop" },
  { e: "🏠", n: "house", k: "home building" },
  { e: "🏡", n: "house_with_garden", k: "home" },
  { e: "🏢", n: "office", k: "building work company" },
  { e: "🏥", n: "hospital", k: "medical" },
  { e: "🏦", n: "bank", k: "money building" },
  { e: "🏨", n: "hotel", k: "stay" },
  { e: "🏫", n: "school", k: "education building" },
  { e: "🏭", n: "factory", k: "industry" },
  { e: "🗼", n: "tokyo_tower", k: "landmark" },
  { e: "🗽", n: "statue_of_liberty", k: "new york landmark" },
  { e: "⛰️", n: "mountain", k: "hill peak" },
  { e: "🌋", n: "volcano", k: "eruption lava" },
  { e: "🏔️", n: "mountain_snow", k: "peak alps" },
  { e: "🏕️", n: "camping", k: "tent outdoors" },
  { e: "🏖️", n: "beach_umbrella", k: "vacation sand" },
  { e: "🏝️", n: "desert_island", k: "vacation tropical" },
  { e: "🌅", n: "sunrise", k: "morning dawn" },
  { e: "🌆", n: "city_sunset", k: "dusk skyline" },
  { e: "🌃", n: "night_with_stars", k: "city evening" },
  { e: "🌌", n: "milky_way", k: "space stars galaxy" },
  { e: "🗺️", n: "world_map", k: "travel geography" },
  { e: "🧭", n: "compass", k: "direction navigate" },
  { e: "🌍", n: "earth_africa", k: "world globe planet" },
  { e: "🌎", n: "earth_americas", k: "world globe planet" },
  { e: "🌏", n: "earth_asia", k: "world globe planet" },
  { e: "🌐", n: "globe_with_meridians", k: "internet web world" },
  { e: "🌙", n: "crescent_moon", k: "night sleep" },
  { e: "🌕", n: "full_moon", k: "night" },
  { e: "🪐", n: "ringed_planet", k: "saturn space" },
  { e: "🌞", n: "sun_with_face", k: "sunny bright" },

  // --- animals & nature ---
  { e: "🐶", n: "dog", k: "puppy pet" },
  { e: "🐱", n: "cat", k: "kitten pet" },
  { e: "🐭", n: "mouse", k: "rodent" },
  { e: "🐹", n: "hamster", k: "pet" },
  { e: "🐰", n: "rabbit", k: "bunny" },
  { e: "🦊", n: "fox_face", k: "fox" },
  { e: "🐻", n: "bear", k: "grizzly" },
  { e: "🐼", n: "panda_face", k: "panda" },
  { e: "🐨", n: "koala", k: "bear australia" },
  { e: "🐯", n: "tiger", k: "cat" },
  { e: "🦁", n: "lion", k: "king cat" },
  { e: "🐮", n: "cow", k: "moo" },
  { e: "🐷", n: "pig", k: "oink" },
  { e: "🐸", n: "frog", k: "toad" },
  { e: "🐵", n: "monkey_face", k: "ape" },
  { e: "🙈", n: "see_no_evil", k: "monkey" },
  { e: "🙉", n: "hear_no_evil", k: "monkey" },
  { e: "🙊", n: "speak_no_evil", k: "monkey" },
  { e: "🐔", n: "chicken", k: "hen" },
  { e: "🐧", n: "penguin", k: "linux bird" },
  { e: "🐦", n: "bird", k: "tweet" },
  { e: "🐤", n: "baby_chick", k: "bird" },
  { e: "🦆", n: "duck", k: "bird quack" },
  { e: "🦅", n: "eagle", k: "bird" },
  { e: "🦉", n: "owl", k: "bird hoot" },
  { e: "🐝", n: "bee", k: "honey insect buzz" },
  { e: "🐛", n: "bug", k: "insect defect issue" },
  { e: "🦋", n: "butterfly", k: "insect" },
  { e: "🐌", n: "snail", k: "slow" },
  { e: "🐞", n: "lady_beetle", k: "ladybug insect" },
  { e: "🐜", n: "ant", k: "insect" },
  { e: "🕷️", n: "spider", k: "web insect" },
  { e: "🐢", n: "turtle", k: "slow tortoise" },
  { e: "🐍", n: "snake", k: "python serpent" },
  { e: "🦄", n: "unicorn", k: "magic horse" },
  { e: "🐙", n: "octopus", k: "sea tentacle" },
  { e: "🐟", n: "fish", k: "sea" },
  { e: "🐬", n: "dolphin", k: "sea flipper" },
  { e: "🐳", n: "whale", k: "sea ocean docker" },
  { e: "🦈", n: "shark", k: "sea jaws" },
  { e: "🐾", n: "paw_prints", k: "animal tracks feet" },
  { e: "🌵", n: "cactus", k: "desert plant" },
  { e: "🌲", n: "evergreen_tree", k: "pine forest" },
  { e: "🌳", n: "deciduous_tree", k: "forest oak" },
  { e: "🌴", n: "palm_tree", k: "tropical beach" },
  { e: "🌱", n: "seedling", k: "sprout grow plant" },
  { e: "🌿", n: "herb", k: "leaf plant" },
  { e: "☘️", n: "shamrock", k: "clover irish" },
  { e: "🍀", n: "four_leaf_clover", k: "luck" },
  { e: "🍁", n: "maple_leaf", k: "autumn canada" },
  { e: "🍂", n: "fallen_leaf", k: "autumn fall" },
  { e: "🍃", n: "leaves", k: "wind plant" },
  { e: "🍄", n: "mushroom", k: "fungus toadstool" },
  { e: "💐", n: "bouquet", k: "flowers gift" },
  { e: "🌹", n: "rose", k: "flower love" },
  { e: "🌷", n: "tulip", k: "flower" },
  { e: "🌸", n: "cherry_blossom", k: "flower sakura spring" },
  { e: "🌼", n: "blossom", k: "flower" },
  { e: "🌻", n: "sunflower", k: "flower" },

  // --- food & drink ---
  { e: "🍎", n: "apple", k: "fruit red" },
  { e: "🍏", n: "green_apple", k: "fruit" },
  { e: "🍊", n: "tangerine", k: "orange fruit" },
  { e: "🍋", n: "lemon", k: "fruit sour" },
  { e: "🍌", n: "banana", k: "fruit" },
  { e: "🍉", n: "watermelon", k: "fruit summer" },
  { e: "🍇", n: "grapes", k: "fruit wine" },
  { e: "🍓", n: "strawberry", k: "fruit berry" },
  { e: "🍒", n: "cherries", k: "fruit" },
  { e: "🍑", n: "peach", k: "fruit butt" },
  { e: "🍍", n: "pineapple", k: "fruit" },
  { e: "🥑", n: "avocado", k: "fruit toast" },
  { e: "🍅", n: "tomato", k: "vegetable fruit" },
  { e: "🌽", n: "corn", k: "vegetable maize" },
  { e: "🥕", n: "carrot", k: "vegetable" },
  { e: "🥐", n: "croissant", k: "bread french" },
  { e: "🍞", n: "bread", k: "loaf toast" },
  { e: "🧀", n: "cheese", k: "dairy" },
  { e: "🥚", n: "egg", k: "breakfast" },
  { e: "🍳", n: "fried_egg", k: "breakfast cooking" },
  { e: "🥞", n: "pancakes", k: "breakfast syrup" },
  { e: "🍟", n: "fries", k: "chips fast food" },
  { e: "🍕", n: "pizza", k: "slice cheese" },
  { e: "🍔", n: "hamburger", k: "burger fast food" },
  { e: "🌭", n: "hotdog", k: "sausage" },
  { e: "🌮", n: "taco", k: "mexican" },
  { e: "🌯", n: "burrito", k: "mexican wrap" },
  { e: "🍿", n: "popcorn", k: "movie snack" },
  { e: "🍩", n: "doughnut", k: "donut sweet" },
  { e: "🍪", n: "cookie", k: "biscuit sweet" },
  { e: "🍰", n: "cake", k: "slice sweet dessert" },
  { e: "🍫", n: "chocolate_bar", k: "sweet candy" },
  { e: "🍬", n: "candy", k: "sweet" },
  { e: "🍭", n: "lollipop", k: "sweet candy" },
  { e: "🍯", n: "honey_pot", k: "sweet bee" },
  { e: "☕", n: "coffee", k: "cafe espresso tea morning" },
  { e: "🍵", n: "tea", k: "green cup" },
  { e: "🍺", n: "beer", k: "pint pub drink" },
  { e: "🍻", n: "beers", k: "cheers pub drink" },
  { e: "🍷", n: "wine_glass", k: "drink red" },
  { e: "🍸", n: "cocktail", k: "martini drink" },
  { e: "🍹", n: "tropical_drink", k: "cocktail vacation" },
  { e: "🍾", n: "champagne", k: "bottle celebrate" },
  { e: "🥂", n: "clinking_glasses", k: "cheers toast celebrate" },
  { e: "🥃", n: "tumbler_glass", k: "whisky drink" },

  // --- activity ---
  { e: "⚽", n: "soccer", k: "football ball" },
  { e: "🏀", n: "basketball", k: "ball hoops" },
  { e: "🏈", n: "football", k: "american nfl" },
  { e: "⚾", n: "baseball", k: "ball" },
  { e: "🎾", n: "tennis", k: "ball racket" },
  { e: "🏐", n: "volleyball", k: "ball" },
  { e: "🎱", n: "8ball", k: "pool billiards" },
  { e: "🏓", n: "ping_pong", k: "table tennis" },
  { e: "🥅", n: "goal_net", k: "sport" },
  { e: "⛳", n: "golf", k: "flag hole" },
  { e: "🎯", n: "dart", k: "target bullseye goal aim" },
  { e: "🎳", n: "bowling", k: "strike pins" },
  { e: "🎮", n: "video_game", k: "gaming controller play" },
  { e: "🕹️", n: "joystick", k: "game arcade" },
  { e: "🎲", n: "game_die", k: "dice random luck" },
  { e: "🧩", n: "jigsaw", k: "puzzle piece" },
  { e: "🎨", n: "art", k: "palette paint design" },
  { e: "🎬", n: "clapper", k: "movie film action" },
  { e: "🎤", n: "microphone", k: "sing karaoke" },
  { e: "🎧", n: "headphones", k: "music listen audio" },
  { e: "🎵", n: "musical_note", k: "music sound" },
  { e: "🎶", n: "notes", k: "music song" },
  { e: "🎸", n: "guitar", k: "music rock" },
  { e: "🎹", n: "musical_keyboard", k: "piano music" },
  { e: "🥁", n: "drum", k: "music beat" },
  { e: "🎺", n: "trumpet", k: "music brass" },
  { e: "🎻", n: "violin", k: "music strings" },
  { e: "🎼", n: "musical_score", k: "music sheet" },

  // --- flags & marks ---
  { e: "🏁", n: "checkered_flag", k: "race finish start" },
  { e: "🚩", n: "triangular_flag_on_post", k: "flag marker" },
  { e: "🏳️", n: "white_flag", k: "surrender" },
  { e: "🏴", n: "black_flag", k: "" },
  { e: "🏴‍☠️", n: "pirate_flag", k: "skull jolly roger" },
  { e: "🎌", n: "crossed_flags", k: "japan celebrate" },
  { e: "🏳️‍🌈", n: "rainbow_flag", k: "pride lgbt" },
  { e: "✅", n: "white_check_mark", k: "done yes tick complete ok" },
  { e: "✔️", n: "heavy_check_mark", k: "done tick yes" },
  { e: "☑️", n: "ballot_box_with_check", k: "checkbox done tick" },
  { e: "❌", n: "x", k: "no wrong cancel fail cross" },
  { e: "❎", n: "negative_squared_cross_mark", k: "no cancel" },
  { e: "➕", n: "heavy_plus_sign", k: "add plus more" },
  { e: "➖", n: "heavy_minus_sign", k: "subtract minus less remove" },
  { e: "➗", n: "heavy_division_sign", k: "divide" },
  { e: "✖️", n: "heavy_multiplication_x", k: "times multiply" },
  { e: "❓", n: "question", k: "help unknown" },
  { e: "❗", n: "exclamation", k: "warning alert important" },
  { e: "‼️", n: "bangbang", k: "double exclamation" },
  { e: "⁉️", n: "interrobang", k: "question exclamation" },
  { e: "⚠️", n: "warning", k: "caution alert danger" },
  { e: "🚫", n: "no_entry_sign", k: "forbidden ban stop prohibited" },
  { e: "🔞", n: "underage", k: "18 nsfw" },
  { e: "♻️", n: "recycle", k: "environment reuse green" },
  { e: "✳️", n: "eight_spoked_asterisk", k: "star" },
  { e: "❇️", n: "sparkle", k: "star shine" },
  { e: "🔆", n: "high_brightness", k: "bright sun light" },
  { e: "〽️", n: "part_alternation_mark", k: "mark" },
  { e: "⚜️", n: "fleur_de_lis", k: "scout decorative" },
  { e: "🔰", n: "beginner", k: "new leaf japanese" },
  { e: "♾️", n: "infinity", k: "forever loop" },
  { e: "〰️", n: "wavy_dash", k: "squiggle" },
  { e: "➰", n: "curly_loop", k: "loop" },
  { e: "🔚", n: "end", k: "arrow finish" },
  { e: "🔙", n: "back", k: "arrow return" },
  { e: "🔜", n: "soon", k: "arrow later" },
  { e: "🔝", n: "top", k: "arrow up" },
  { e: "🆕", n: "new", k: "badge fresh" },
  { e: "🆓", n: "free", k: "badge no cost" },
  { e: "🆗", n: "ok", k: "okay badge" },
  { e: "🆒", n: "cool", k: "badge" },
  { e: "➡️", n: "arrow_right", k: "east direction next" },
  { e: "⬅️", n: "arrow_left", k: "west direction back previous" },
  { e: "⬆️", n: "arrow_up", k: "north direction" },
  { e: "⬇️", n: "arrow_down", k: "south direction" },
  { e: "↗️", n: "arrow_upper_right", k: "northeast" },
  { e: "↘️", n: "arrow_lower_right", k: "southeast" },
  { e: "↙️", n: "arrow_lower_left", k: "southwest" },
  { e: "↖️", n: "arrow_upper_left", k: "northwest" },
  { e: "↔️", n: "left_right_arrow", k: "horizontal" },
  { e: "↕️", n: "arrow_up_down", k: "vertical" },
  { e: "🔄", n: "arrows_counterclockwise", k: "refresh sync reload" },
  { e: "🔁", n: "repeat", k: "loop replay" },
  { e: "🔀", n: "twisted_rightwards_arrows", k: "shuffle random" },
  { e: "▶️", n: "arrow_forward", k: "play" },
  { e: "⏸️", n: "pause_button", k: "pause" },
  { e: "⏯️", n: "play_or_pause_button", k: "play pause" },
  { e: "⏹️", n: "stop_button", k: "stop" },
  { e: "⏭️", n: "next_track_button", k: "skip forward" },
  { e: "⏮️", n: "previous_track_button", k: "skip back" },

  // --- misc dots & shapes ---
  { e: "🔴", n: "red_circle", k: "dot record" },
  { e: "🟠", n: "orange_circle", k: "dot" },
  { e: "🟡", n: "yellow_circle", k: "dot" },
  { e: "🟢", n: "green_circle", k: "dot ok pass" },
  { e: "🔵", n: "large_blue_circle", k: "dot" },
  { e: "🟣", n: "purple_circle", k: "dot" },
  { e: "⚫", n: "black_circle", k: "dot" },
  { e: "⚪", n: "white_circle", k: "dot" },
  { e: "🟥", n: "red_square", k: "block" },
  { e: "🟩", n: "green_square", k: "block" },
  { e: "🟦", n: "blue_square", k: "block" },
  { e: "🔶", n: "large_orange_diamond", k: "shape" },
  { e: "🔷", n: "large_blue_diamond", k: "shape" },
  { e: "🔹", n: "small_blue_diamond", k: "shape bullet" },
  { e: "🔸", n: "small_orange_diamond", k: "shape bullet" },
  { e: "▪️", n: "black_small_square", k: "bullet dot" },
  { e: "▫️", n: "white_small_square", k: "bullet dot" },
  { e: "◾", n: "black_medium_small_square", k: "bullet" },
  { e: "💠", n: "diamond_shape_with_a_dot_inside", k: "gem shape" },
  { e: "🔺", n: "small_red_triangle", k: "up shape" },
  { e: "🔻", n: "small_red_triangle_down", k: "down shape" },
];

// Alternate shortcodes → canonical `n`.
export const ALIASES: Record<string, string> = {
  thumbsup: "+1",
  thumbup: "+1",
  "+1": "+1",
  thumbsdown: "-1",
  thumbdown: "-1",
  "-1": "-1",
  smiley_face: "smiley",
  happy: "smile",
  laugh: "laughing",
  lol: "joy",
  lmao: "rofl",
  hankey: "poop",
  shit: "poop",
  crap: "poop",
  heart_red: "heart",
  check: "white_check_mark",
  tick: "heavy_check_mark",
  cross: "x",
  no: "x",
  done: "white_check_mark",
  ok_sign: "ok_hand",
  plus1: "+1",
  celebrate: "tada",
  party: "tada",
  rocketship: "rocket",
  ship_it: "rocket",
  bug_report: "bug",
  idea: "bulb",
  warn: "warning",
  danger: "warning",
  smiling: "blush",
  think: "thinking",
  hmm: "thinking",
  eyeroll: "roll_eyes",
  cool_face: "sunglasses",
  fingers_crossed: "crossed_fingers",
  pray_hands: "pray",
  thanks: "pray",
  clapping: "clap",
  star_full: "star",
  sparkle_stars: "sparkles",
  flame: "fire",
  lit: "fire",
  hundred: "100",
  perfect: "100",
};

/** shortcode (canonical or alias) → glyph */
export const BY_SHORTCODE: Map<string, string> = (() => {
  const m = new Map<string, string>();
  for (const { e, n } of EMOJI) m.set(n, e);
  for (const [alias, canonical] of Object.entries(ALIASES)) {
    const g = m.get(canonical);
    if (g && !m.has(alias)) m.set(alias, g);
  }
  return m;
})();
