const scenes=[...document.querySelectorAll('.scene')];
const cuts=[{scene:5,seconds:30},{scene:0,seconds:12},{scene:1,seconds:12},{scene:2,seconds:12},{scene:3,section:'10',seconds:12},{scene:3,section:'12',seconds:12},{scene:3,section:'20',seconds:12},{scene:3,section:'9',seconds:10},{scene:4,seconds:10}];
let current=0,playing=false,timer=null,jumpTimer=null;
function fit(){document.documentElement.style.setProperty('--scale',Math.min(innerWidth/1920,innerHeight/1080))}addEventListener('resize',fit);fit();
function jump(section){clearTimeout(jumpTimer);if(window.jumpDocument)window.jumpDocument(section);else jumpTimer=setTimeout(()=>jump(section),200);document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('selected',b.dataset.section===section));const copy={'10':['写下的，<br>都好看。','从标题到表格，<br>给文字清楚的层次。'],'12':['让代码，<br>也有颜色。','语法高亮与行号，<br>读起来，一目了然。'],'20':['复杂公式，<br>清楚表达。','矩阵、积分与推导，<br>让每个符号各就其位。'],'9':['文字之外，<br>也有风景。','图片与文字相遇，<br>把喜欢的画面写进来。'],'1':['写下的，<br>都好看。','完整测试文档，<br>在这里，自由翻阅。']}[section];if(copy){document.querySelector('#render-title').innerHTML=copy[0];document.querySelector('#render-description').innerHTML=copy[1]}}
function schedule(){clearTimeout(timer);if(playing)timer=setTimeout(()=>{if(current===cuts.length-1){pause();return}go(current+1)},cuts[current].seconds*1000)}
function go(n){current=Math.max(0,Math.min(cuts.length-1,n));const cut=cuts[current];scenes.forEach(s=>s.classList.toggle('active',Number(s.dataset.index)===cut.scene));document.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('current',Number(b.dataset.scene)===(cut.scene===2?1:cut.scene)));document.querySelector('#counter').textContent=String(current+1).padStart(2,'0')+' / '+String(cuts.length).padStart(2,'0');document.querySelector('#progress').style.width=((current+1)/cuts.length*100)+'%';history.replaceState(null,'','#'+(current+1));if(cut.section)jump(cut.section);schedule()}
function pause(){playing=false;clearTimeout(timer);document.querySelector('#play').textContent='▶ 自动播放'}
function togglePlay(){if(playing)pause();else{if(current===cuts.length-1)go(0);playing=true;document.querySelector('#play').textContent='Ⅱ 暂停';schedule()}}
function step(n){pause();go(current+n)}
function full(){if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{})}
document.querySelector('#prev').onclick=()=>step(-1);document.querySelector('#next').onclick=()=>step(1);document.querySelector('#play').onclick=togglePlay;document.querySelector('#fullscreen').onclick=full;document.querySelector('#record').onclick=()=>document.body.classList.toggle('recording');document.querySelector('#help-button').onclick=()=>document.querySelector('#help').hidden=false;document.querySelector('#help-close').onclick=()=>document.querySelector('#help').hidden=true;
document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{pause();go(cuts.findIndex(c=>c.scene===Number(b.dataset.scene)))});document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{pause();const index=cuts.findIndex(c=>c.section===b.dataset.section);if(index>=0)go(index);else jump(b.dataset.section)});
addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const k=e.key.toLowerCase();if(['arrowright','arrowleft',' ','a','r','f','h','1','2','3','4'].includes(k))e.preventDefault();if(k==='arrowright'||k===' ')step(1);if(k==='arrowleft')step(-1);if(k==='a')togglePlay();if(k==='r'){pause();go(0)}if(k==='f')full();if(k==='h')document.body.classList.toggle('recording');if(k==='1'||k==='2'||k==='3'||k==='4'){pause();go({'1':0,'2':1,'3':2,'4':4}[k])}if(k==='escape')document.querySelector('#help').hidden=true});
addEventListener('contextmenu',e=>{e.preventDefault();step(1)});go(Math.max(0,Math.min(cuts.length-1,(parseInt(location.hash.slice(1))||1)-1)));
document.querySelector('.logo').onclick=e=>{e.preventDefault();pause();go(0)};
